services:
  server:
    build:
      context: .
    env_file:
      - .env.dev
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017

  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: '2g' # Set shared memory size
